### ISSUE TITLE
Agent not placing the objects in the correct pose

### ISSUE THREAD

**Issue by nnsriram97** [allenai/ai2thor-rearrangement#20]
I see sometimes that even when the goal state is visible, the agent doesn't seem to place the object in the right place and there's some difference in the pose of the placed object with that of the goal. This can be noticed from the first example of the expert from `valid` dataset.

Here's a video from the expert where it is trying to rearrange the toilet paper but is unsuccessful in placing it at the right place and hence keeps retrying. 

https://user-images.githubusercontent.com/11937559/120375753-00f56380-c2d0-11eb-89f1-b00167b23941.mp4

**Comment by Lucaweihs** [comment]
Thanks for reporting this @nnsriram97 ! I haven't had a chance to debug this today but I'll try to make some time tomorrow. My guess is that we might (unfortunately) have to save fixing this issue for a future iteration of this challenge as otherwise comparisons against other models on the leaderboard will be unfair.

**Comment by AaronAnima** [comment]
> Thanks for reporting this @nnsriram97 ! I haven't had a chance to debug this today but I'll try to make some time tomorrow. Just FYI: my guess is that we might (unfortunately) have to save fixing this issue for a future iteration of this challenge as otherwise comparisons against other models on the leaderboard will be unfair.

What date do you expect to fix this problem :)?

**Comment by Lucaweihs** [comment]
This should be fixed now, let me know if you find any more edge cases.
